builds:
- binary: qbee-cli
  id: qbee-cli
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  - arm
- binary: qbee-cli
  id: qbee-cli-macos
  goos:
  - darwin
  goarch:
  - amd64
  - arm64
signs:
  - signature: "${artifact}.dmg"
    ids:
    - qbee-cli-macos # here we filter the macos only build id
    # you'll need to have gon on PATH
    cmd: gon
    # you can follow the gon docs to properly create the gon.hcl config file:
    # https://github.com/mitchellh/gon
    args:
    - gon.hcl
    artifacts: all