version: 2

project_name: qbee-cli

builds:
  - id: qbee-cli

    main: ./cmd/

    env:
      - CGO_ENABLED=0

    gcflags:
      - -trimpath

    ldflags:
      - -s 
      - -w 
      - -X go.qbee.io/client.Version={{.Version}}

    targets:
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - linux_amd64

    mod_timestamp: "{{ .CommitTimestamp }}"

# gomod:
  # proxy: true

changelog:
  use: github-native

sboms:
  - artifacts: source

checksum:
  name_template: checksums.txt

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

source:
  enabled: true

notarize:
  macos:
    - enabled: "true"
      sign:
        certificate: "{{ .Env.MACOS_SIGN_P12 }}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"

      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
