// Copyright 2025 qbee.io
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package client

// Permission represents a permission in the system.
type Permission string

const (
	// AnalysisRead allows comparison of selected devices from the fleet.
	// It provides read-only access to the Analysis page visible in the qbee web interface.
	AnalysisRead Permission = "analysis:read"

	// AuditRead allows viewing of audit logs and activity history within the account.
	// This includes who performed what actions (user, device, or configuration changes)
	// for security and traceability purposes.
	AuditRead Permission = "audit:read"

	// BillingRead grants visibility into the billing overview—subscription plan,
	// usage information, and invoices. It does not allow changes.
	BillingRead Permission = "billing:read"

	// BillingManage allows managing billing settings such as payment methods,
	// subscription plans, and invoice information.
	BillingManage Permission = "billing:manage"

	// BootstrapKeysRead allows viewing of bootstrap keys used for enrolling devices.
	// Users with this permission can list keys but cannot create or delete them.
	BootstrapKeysRead Permission = "bootstrap-keys:read"

	// BootstrapKeysManage allows creating, revoking, or managing bootstrap keys
	// that enable device registration in qbee.
	BootstrapKeysManage Permission = "bootstrap-keys:manage"

	// CompanyRead permits viewing company-level settings such as organization
	// details, contact info, and account metadata.
	CompanyRead Permission = "company:read"

	// CompanyManage allows editing company-level settings, including modifying
	// account details or metadata that apply globally across the organization.
	CompanyManage Permission = "company:manage"

	// ConfigurationRead grants read-only access to configurations assigned to devices,
	// groups or tags, including templates, rules, and parameter sets.
	ConfigurationRead Permission = "configuration:read"

	// ConfigurationManage allows creating, updating, and deleting configurations,
	// assigning them to devices, groups or tags.
	ConfigurationManage Permission = "configuration:manage"

	// CVERead allows viewing vulnerability (CVE) information related to devices,
	// such as detected vulnerabilities and their severity.
	CVERead Permission = "cve:read"

	// CVEManage permits managing vulnerability-related settings such as suppression.
	CVEManage Permission = "cve:manage"

	// DeviceApprove allows approving pending devices that request enrollment
	// in the system.
	DeviceApprove Permission = "device:approve"

	// DeviceRead provides visibility into device lists, metadata, and live status,
	// including connection state and inventory data.
	DeviceRead Permission = "device:read"

	// DeviceManage allows performing management actions on devices such as deleting,
	// moving between groups.
	DeviceManage Permission = "device:manage"

	// FilesRead allows listing and downloading files from the managed file repository
	// used in configurations or device file management.
	FilesRead Permission = "files:read"

	// FilesManage allows uploading, deleting, and organizing files in the file
	// repository.
	FilesManage Permission = "files:manage"

	// RemoteAccessConnect allows initiating remote access sessions to devices
	// using qbee-cli or web UI.
	RemoteAccessConnect Permission = "remote-access:connect"

	// RemoteAccessManage allows configuring of remote access settings (port mapping).
	RemoteAccessManage Permission = "remote-access:manage"

	// ReportsRead grants access to view system and compliance reports generated by qbee-agent.
	ReportsRead Permission = "reports:read"

	// ReportsAcknowledge allows marking reports or alerts as acknowledged.
	ReportsAcknowledge Permission = "reports:acknowledge"

	// RolesRead allows viewing defined roles and their associated permissions
	// in the organization’s RBAC setup.
	RolesRead Permission = "roles:read"

	// RolesManage allows creating, editing, or deleting roles and modifying their
	// permissions.
	RolesManage Permission = "roles:manage"

	// UsersRead allows viewing the list of users, their roles, and statuses
	// within the organization.
	UsersRead Permission = "users:read"

	// UsersManage allows inviting new users, removing existing ones,
	// and changing their assigned roles or access levels.
	UsersManage Permission = "users:manage"
)
